export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  APPLICATION_DUPLICATE: 'APPLICATION_DUPLICATE',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
  APPLICATION_ALREADY_HANDLED: 'APPLICATION_ALREADY_HANDLED',
  CANNOT_APPLY_OWN_TRIP: 'CANNOT_APPLY_OWN_TRIP',
  TRIP_FULL: 'TRIP_FULL',
  ALREADY_TRIP_MEMBER: 'ALREADY_TRIP_MEMBER',
  NOT_TRIP_OWNER: 'NOT_TRIP_OWNER'
} as const;
